@startuml C4-2-Diagrama-de-containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(User, "Usuário", "Cria e consulta propostas/projetos")
Person(PMO, "PMO", "Aprova propostas")
Person(Team, "Equipe", "Aprova propostas")
Person(Manager, "Gerente de Área", "Aprova propostas")
Person(QA, "QA Lead", "Consulta logs de auditoria")

System_Boundary(s1, "Gestão PPM") {
  System(FrontEnd, "Interface Web", "Exibe telas para cadastro, aprovação e consulta")
  System(BackEnd, "API RESTful", "Regras de negócio, autenticação, fluxo de aprovação, auditoria, notificações")
  ContainerDb(Database, "Database", "SQL/DB", "Armazena dados de prospostas e projetos")
}

System_Ext(Email, "Serviço de E-mail", "Envia notificações")
System_Ext(ERP, "Sistema ERP", "Integra dados futuros")
System_Ext(BI, "Ferramenta BI", "Consulta dados futuros")
System_Ext(Monitoring, "Ferramenta de observabilidade", "Armazena e categoriza os logs")
System_Ext(Auth, "Ferramenta de autenticação", "Autentica o usuário e retorna a sessão")

Rel(User, FrontEnd, "Acessa via navegador", "")
Rel(PMO, FrontEnd, "Acessa via navegador", "")
Rel(Team, FrontEnd, "Acessa via navegador", "")
Rel(Manager, FrontEnd, "Acessa via navegador", "")
Rel(QA, Monitoring, "Consulta os logs", "")

Rel(FrontEnd, Auth, "Autentica o usuário")
Rel(BackEnd, Auth, "Valida a sessão do usuário")
Rel(FrontEnd, BackEnd, "Usa APIs RESTful")
Rel(BackEnd, Database, "Lê/Grava dados")
Rel(BackEnd, Email, "Envia e-mails via SMTP/API")
Rel(ERP, BackEnd, "Integração futura via API")
Rel(BI, BackEnd, "Consulta dados futuros via API")
Rel(BackEnd, Monitoring, "Informa os logs a serem registrados")

LAYOUT_WITH_LEGEND()
@enduml